version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: rollup-plugin-uglify
    versions:
    - 4.0.0
